export const {
  PORT = 3000,
  SALT_ROUNDS = 10,
  TOKEN_EXPIRE = '1h',
  JWT_SECRET = 'jwtsecret',
  AUTH_HEADER_TOKEN = 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQWxhbiIsImVtYWlsIjpudWxsLCJpYXQiOjE3NTA3MjE5NjYsImV4cCI6MTc1MDcyNTU2Niwic3ViIjoiYzJhYzRiZDctNDdmNC0xMWYwLWJkMDAtMzQ2ZjI0YTQxZGE0In0.mm2NW5vYjzgaOFJ7evXtxoxVsMx5GUHYKlT-jS51qtU'
} = process.env
