export const {
  PORT = 3000,
  SALT_ROUNDS = 10,
  JWT_SECRET = 'jwtsecret',
  AUTH_HEADER_TOKEN = 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQWxhbiIsImVtYWlsIjpudWxsLCJpYXQiOjE3NTA3MjE5NjYsImV4cCI6MTc1MDcyNTU2Niwic3ViIjoiYzJhYzRiZDctNDdmNC0xMWYwLWJkMDAtMzQ2ZjI0YTQxZGE0In0.mm2NW5vYjzgaOFJ7evXtxoxVsMx5GUHYKlT-jS51qtU',
  ACCESS_TOKEN_EXP = '5m',
  REFRESH_TOKEN_EXP = '7d',
  BUCKET_SIZE = 100,
  REFILL_INTERVAL = 60000,
  TOKEN_RATE = 1
} = process.env
