CREATE DATABASE todos;
USE todos;


DROP TABLE IF EXISTS users;
CREATE TABLE users (
	id BINARY(16) PRIMARY KEY DEFAULT (UUID_TO_BIN(UUID())),
    name VARCHAR(50) NOT NULL UNIQUE,
    email VARCHAR (50) DEFAULT NULL UNIQUE,
    password VARCHAR(74)
);
ALTER TABLE users
MODIFY COLUMN password VARCHAR(225);


CREATE TABLE tasks (
	id INT AUTO_INCREMENT PRIMARY KEY,
    user BINARY(16) NOT NULL,
    title VARCHAR (50) NOT NULL,
    description VARCHAR(80) DEFAULT NULL,
    date TIMESTAMP DEFAULT(SYSDATE()),
    FOREIGN KEY (user) REFERENCES users (id)
);
